### ISSUE TITLE
Returning a null success value when using the error-callback.

### ISSUE THREAD

**Issue by lghamie** [darylturner/node-netconf#1]
I'm trying to promisfy this library, and i'm having a problem since when you return using the error callback, both the first and the second parameter return values.

According to: http://bluebirdjs.com/docs/api/promise.promisify.html  The only needed change should be something like this:

In netconf.js  line 105 change:
`return callback(new Error(message), message);`
to:
`return callback(new Error(JSON.stringify(message)), null);`

**Comment by darylturner** [comment]
Hi, I agree that the current way this is handled isn't idiomatic. I'll get this updated shortly.

**Comment by darylturner** [comment]
Hi, it should now return the original message in a custom rpcError and leave the 'success' value as null now. I've bumped the major version number just to be on the safe side with changing the output values. Please re-open the issue if you have any more problems.
