### ISSUE TITLE
Missing base capability in hello error seen on Cisco CSR1k

### ISSUE THREAD

**Issue by phpetty** [darylturner/node-netconf#4]
Hi Daryl,

Thank you for writing and maintaining this package. I'm pretty new to NETCONF and have been using this package to play around with a Cisco CSR1k. I am was trying to follow your netconf-get example but my RPC callback wasn't being called. After adding some debugs to netconf.js, I was able to work that the following error was in the receive buffer (and because I didn't get a reply to my RPC message, I don't get a callback):
```
<!-- Error: missing base capability in hello (closing session) -->
```

It looks like Cisco routers expect the 'urn:ietf:params:netconf:base:1.0' capability at a minimum, but this package is currently only sending 'urn:ietf:params:xml:ns:netconf:base:1.0'. I went ahead and modified netconf.js per the diffs below and I can confirm that it is now working:
```
phpetty@phpetty-ubuntu:~/node$ diff -pW5 ../netconf/node_modules/netconf/lib/netconf.js node_modules/netconf/lib/netconf.js 
*** ../netconf/node_modules/netconf/lib/netconf.js      2017-05-31 13:58:35.314361772 +1000
--- node_modules/netconf/lib/netconf.js 2017-05-31 13:33:11.798430191 +1000
*************** Client.prototype = {
*** 182,192 ****
              hello: {
                  $: { xmlns: 'urn:ietf:params:xml:ns:netconf:base:1.0' },
                  capabilities: {
!                     capability: 'urn:ietf:params:xml:ns:netconf:base:1.0'
                  }
              }
          };
!         const builder = new xml2js.Builder();
          const xml = builder.buildObject(message) + '\n' + DELIM;
          this.netconf.write(xml);
      }
--- 182,195 ----
              hello: {
                  $: { xmlns: 'urn:ietf:params:xml:ns:netconf:base:1.0' },
                  capabilities: {
!                     capability: [
!                         'urn:ietf:params:netconf:base:1.0',
!                         'urn:ietf:params:xml:ns:netconf:base:1.0'
!                     ]
                  }
              }
          };
!         const builder = new xml2js.Builder({ headless: true });
          const xml = builder.buildObject(message) + '\n' + DELIM;
          this.netconf.write(xml);
      }
phpetty@phpetty-ubuntu:~/node$
```

Would you consider adding this change to your package and pushing it out to npm?

Further to this, a future enhancement could be to add a capabilities array to the client parameters so that users can define their own additional capabilities.

**Comment by darylturner** [comment]
Hi, i merged in a pull request to add some better Cisco support last month which may already cover what you need.

https://github.com/darylturner/node-netconf/pull/3

I haven't yet published to NPM as this will cause a breaking change. Would you be able to clone the repo and see if any more changes are required?

The reason I'm holding back on publishing a new major version to NPM is I would like to separate the Cisco/Juniper specific bits into submodules. Hopefully this would make things more maintainable if new features need to be added.

Thanks,
Daryl.

**Comment by phpetty** [comment]
Hi Daryl,

I have tested the latest repo and I can confirm that I don't see the missing capabilities error.

I'm a little confused about the IOSClose function that has been added. Do you know much about this?

I tested sending a close-session request directly from the CLI to my CSR1k and the SSH session terminated. I'm wondering if this is something that has been fixed in more recent IOS versions than what this was tested against. The version that was tested against in the code comments was 12.2(58)SE2 which I believe is about 5 years old. I think it would be better for users to handle this in their script than in this package as my callback to IOSClose() isn't called, however it is for close(). Someone reading netconf.js might assume they need to use IOSClose() as they are using a Cisco device and waste time debugging this. I see there being arguments for and against keeping this function - maybe just a big comment that this is only for older IOS versions? I'm not overly fussed either way, just thought I'd point this out.

Kind regards,
Phil

**Comment by darylturner** [comment]
Hi Phil,

Thank you for testing. I agree; dealing with the idiosyncrasies of every vendor implementation probably isn't best dealt with in the module. My goal is to keep the core parts fairly RFC standard and allow the user to workaround vendor bugs using the raw RPC functions. That is why I'm currently holding off on the new NPM version until this rejig has been completed.

My problem has always been access to test against recent versions of IOS-XE/XR without a service contract. Juniper make it pretty easy to download a vSRX to test against but it looks like the most recent version I can get for free from Cisco is 2 years old.

I'll keep the issue open as allowing the user to override the capabilities array should be a fairly trivial change.

Thanks,
Daryl.
